export const Colors = {
  BACKGROUNDWITHE: '#FFF',
  TRANSPARENT: 'rgba(0, 0, 0, 0.4)',
  BLACK: '#000',
  BGLOGIN: '#fff',
  TEXTBOX: '#5c5953',
  BOX: '#fff',
  GREEN: '#2FA23B',
  GREENCOMP: '#2AB083',
  RED: '#CD191E',
  TEXTINPUT: '#cecdd3',
  TEXT: '#a5a7b0',
  ICONS: '#fe0000',
  BORDERCOLOR: '#cecdd3',
  TEXTINPUT: '#8F98C1',
  VIEWDETAILS: '#c67aff',
  CONTAINER: '#fafafa',
};
